### PR TITLE
Bugfix: fixes an issue with multiple buttons in the last td of the ta…

### PR DESCRIPTION
**Pull request by vanhoog**
## Changelog

```markdown

### Changed
Styles inside the _table.scss to fix multiple styling errors
```

### CODE REVIEW

**Comment by ceesvanegmond** [comment]
@vanhoog Please fill in the first post correctly (title/changelog), we'll see what's changed instantly :-)

**Comment by ceesvanegmond** [comment]
@vanhoog Again -> @vanhoog Please fill in the first post correctly (title/changelog), we'll see what's changed instantly :-)

**Review by RutgerKooijman — DISMISSED** [review]

**Comment by ceesvanegmond** [comment]
@vanhoog Please fix conflicted files.

**Review by RutgerKooijman — COMMENTED** [review]
just width will do, no max width

**Review by johnhout — DISMISSED** [review]

**Comment by RutgerKooijman** [comment]
@vanhoog conflicted, please fix

**Review by RutgerKooijman — APPROVED** [review]

**Pull request merged**
