### PR TITLE
Chore: makes sure that the first table cell and table head which cont…

### PR DESCRIPTION
**Pull request by vanhoog**
…ain the checkboxes have a different padding, also makes sure the table cell and table head next to these will have a proper padding so that they align with the title

## Title
Styles the First TH and TD containing a checkbox

## Changelog
```markdown
### Changed
 Styles the First TH and TD containing a checkbox to be smaller, making sure that the first TEXT TD or TH is aligned with the page title.

```

### CODE REVIEW

**Review by ceesvanegmond — DISMISSED** [review]

**Comment by RutgerKooijman** [comment]
Can you resolve the conflicts please?

**Comment by RutgerKooijman** [comment]
@vanhoog ?

**Review by johnhout — CHANGES_REQUESTED** [review]
After conflict resolvement approved.

**Comment by RutgerKooijman** [comment]
After conflict resolvement approved.

**Review by RutgerKooijman — CHANGES_REQUESTED** [review]
Fine, but conflicted. Please solve

**Review by RutgerKooijman — DISMISSED** [review]

**Review by Emroni — DISMISSED** [review]

**Review by johnhout — DISMISSED** [review]

**Pull request merged**
