### PR TITLE
WIP: Chore: Enable the sidebar search field

### PR DESCRIPTION
**Pull request by bartjust**
This will enable the search field in the left sidebar

### CODE REVIEW

**Comment by ceesvanegmond** [comment]
@bartjust Does the 'search' functionality work?

**Comment by RutgerKooijman** [comment]
@johnhout and @bartjust and @ceesvanegmond is this a Trello card? Should't the search be on the right side?

**Comment by bartjust** [comment]
@ceesvanegmond @RutgerKooijman I had to enable this so @johnhout could work on it. This means it is still work in progress.

**Comment by ceesvanegmond** [comment]
@bartjust 👍

**Review by RutgerKooijman — CHANGES_REQUESTED** [review]
Shouldn't we put the field on the right above the list?

**Comment by bartjust** [comment]
I believe it should be aligned with the filter button. They both have a search functionality.

**Pull request closed without merging**
